Repository 2024-Summer-Bootcamp-Team-N/Backend, pull requests merged in 2024-07, with the labels that each got.

#13 [fix] 환경변수 수정
  db.sqlite3
  docker-compose.yml
  myapp/__pycache__/urls.cpython-311.pyc
  myapp/__pycache__/views.cpython-311.pyc
  myapp/migrations/0001_initial.py
  myapp/models.py
  myapp/serializers.py
  myapp/urls.py
  myapp/views.py
  myproject/__pycache__/settings.cpython-311.pyc
  myproject/__pycache__/urls.cpython-311.pyc
  myproject/settings.py
  myproject/urls.py
  requirements.txt
Labels: 문서작성, 환경설정

#16 [feat] 카카오지도 api 연동 완료
  myapp/views.py
  myproject/templates/index.html
Labels: 기능구현, 환경설정

#21 [feat] MVT 패턴 적용완료
  .gitignore
  Dockerfile
  apps/entry/migrations/0001_initial.py
  apps/entry/migrations/0002_category_monthly.py
  apps/entry/migrations/__init__.py
  apps/entry/models.py
  apps/entry/serializers.py
  apps/entry/tests.py
  apps/entry/urls.py
  apps/entry/views.py
  apps/info/models.py
  apps/info/serializers.py
  apps/info/tests.py
  apps/info/urls.py
  apps/info/views.py
  apps/options/models.py
  apps/options/serializers.py
  apps/options/tests.py
  apps/options/urls.py
  apps/options/views.py
  apps/users/models.py
  apps/users/serializers.py
  apps/users/tests.py
  apps/users/urls.py
  apps/users/views.py
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  db.sqlite3
  manage.py
  myapp/__pycache__/__init__.cpython-311.pyc
  myapp/__pycache__/urls.cpython-311.pyc
  myapp/__pycache__/views.cpython-311.pyc
  myapp/admin.py
  myapp/apps.py
  myapp/migrations/0001_initial.py
  myapp/models.py
  myapp/serializers.py
  myapp/tests.py
  myapp/urls.py
  myapp/views.py
  myproject/__pycache__/__init__.cpython-311.pyc
  myproject/__pycache__/settings.cpython-311.pyc
  myproject/__pycache__/urls.cpython-311.pyc
  myproject/__pycache__/wsgi.cpython-311.pyc
  myproject/templates/index.html
  myproject/urls.py
  requirements.txt
Labels: 기능구현, 환경설정

#26 [feat] mysql 세팅 완료
  Dockerfile
  config/settings.py
  docker-compose.yml
  requirements.txt
Labels: 기능구현, 환경설정

#28 [chore] rds 연동 완료
  Dockerfile
  docker-compose.yml
Labels: 환경설정

#32 [feat] entry 1차 수정 완료.
  apps/entry/serializers.py
  apps/entry/urls.py
  apps/entry/views.py
Labels: 기능구현

#34 [feat] 주소 입력 후 좌표 반환기능 구현 완료
  apps/entry/urls.py
  apps/entry/views.py
  jp.py
Labels: 기능구현

#39 [feat] 도커에 셀러리와 레빗엠큐 연동 완료.
  Dockerfile
  __init__.py
  config/celery.py
  config/settings.py
  db.sqlite3
  docker-compose.yml
  jp.py
  requirements.txt
  tasks.py
Labels: 기능구현

#43 [feat] 로그아웃 수정
  apps/info/models.py
  apps/info/serializers.py
  apps/info/views.py
  apps/users/serializers.py
  apps/users/views.py
  config/settings.py
  debug.log
Labels: 기능구현

#45 [feat] 로그인,로그아웃 및 토큰 기능 리팩토링 완료.
  apps/users/authentication.py
  apps/users/urls.py
  apps/users/views.py
  config/celery.py
  config/settings.py
  debug.log
  docker-compose.yml
  rabbitmq/advanced.config
  rabbitmq/definitions.json
  rabbitmq/dockerfile.rabbitmq
  rabbitmq/rabbitmq.conf
Labels: 기능구현, 리팩토링

#47 [feat] entry 수정
  apps/entry/migrations/0004_regions_latitude_regions_longitude.py
  apps/entry/migrations/0005_types_pricerangemax.py
  apps/entry/migrations/0006_alter_types_depositrangemax_and_more.py
  apps/entry/models.py
  apps/entry/serializers.py
  apps/entry/views.py
  apps/info/urls.py
  apps/info/views.py
  config/settings.py
  config/urls.py
  debug.log
Labels: 기능구현

#53 [refactor] 엔드포인트 1차 수정 완료.
  apps/entry/urls.py
  apps/info/urls.py
  apps/info/views.py
  apps/users/urls.py
  config/api_urls.py
  config/urls.py
Labels: 리팩토링

#55 [feat] url api db 연동
  apps/info/models.py
  apps/info/serializers.py
  apps/info/views.py
Labels: 기능구현

#58 [feat] 크롤링 기능 구현 완료.
  .dockerignore
  Dockerfile
  Dockerfile.celery
  apps/info/views.py
  apps/options/migrations/0001_initial.py
  apps/options/migrations/0002_remove_roominfo_created_at_alter_roominfo_price.py
  apps/options/migrations/0003_alter_roominfo_price.py
  apps/options/migrations/__init__.py
  apps/options/models.py
  apps/options/serializers.py
  apps/options/tasks.py
  apps/options/urls.py
  apps/options/views.py
  config/__init__.py
  config/api_urls.py
  config/celery.py
  config/settings.py
  config/urls.py
  docker-compose.yml
  rabbitmq/Dockerfile.rabbitmq
  requirements.txt
  tasks.py
Labels: 기능구현

#60 [feat] rabbitMQ 환경변수 추가
  .gitignore
  rabbitmq/rabbitmq-env.conf
  rabbitmq/rabbitmq.conf
Labels: 기능구현, 환경설정

#62 [fix] 월세/ 보증금 선택시 URL이 출력이 안되는 문제: post 메서드 types에 변수 지정 오류 수정 / 매물이 적은 경우:…
  apps/entry/views.py
  apps/info/views.py
Labels: 오류수정

#67 [feat] 통신구현 전 도커컴포즈 파일 수정.
  Dockerfile
  apps/options/views.py
  config/settings.py
Labels: 기능구현, 오류수정

#68 [feat] 통신 구현 1차 완료
  Dockerfile
  apps/__init__.py
  apps/entry/apps.py
  apps/info/apps.py
  apps/options/apps.py
  apps/users/apps.py
  chat/__init__.py
  chat/admin.py
  chat/apps.py
  chat/consumers.py
  chat/migrations/__init__.py
  chat/models.py
  chat/routing.py
  chat/templates/websocket_test.html
  chat/tests.py
  chat/views.py
  config/asgi.py
  config/settings.py
  config/urls.py
  docker-compose.yml
  requirements.txt
Labels: 기능구현

#71 [feat] 도커 이미지 변경 및 기타 수정.
  .dockerignore
  Dockerfile
  Dockerfile.celery
  config/settings.py
  docker-compose.yml
  supervisord.conf
Labels: 기능구현, 환경설정

#72 [feat] 챗지피티연동완
  Dockerfile
  Dockerfile.celery
  chat/chatgpt.py
  chat/consumers.py
  chat/templates/websocket_test.html
  config/settings.py
  requirements.txt
  supervisord.conf
Labels: 기능구현

#75 [docs] settings.py 수정완
  config/settings.py
  requirements.txt
Labels: 문서작성

#78 [refactor] gpt 응답수정 완료.
  chat/chatgpt.py
  chat/consumers.py
  chat/templates/websocket_test.html
  requirements.txt
Labels: 리팩토링

#81 [feat] 2차 크롤링 구현완료
  config/settings.py
Labels: 기능구현

#84 [feat] 레디스 연동
  Dockerfile
  chat/chatgpt.py
  chat/consumers.py
  config/settings.py
  docker-compose.yml
  requirements.txt
Labels: 기능구현

#85 [feat] 2차 크롤링
  apps/options/migrations/0001_initial.py
  apps/options/migrations/0002_auto_20240720_1540.py
  apps/options/migrations/0002_remove_roominfo_created_at_alter_roominfo_price.py
  apps/options/migrations/0003_alter_roominfo_price.py
  apps/options/models.py
  apps/options/serializers.py
  apps/options/urls.py
  apps/options/views.py
Labels: 기능구현

#90 [feat] 젠킨스 도커 세팅.
  docker-compose-jenkins.yml
  jenkins.Dockerfile
Labels: 기능구현, 환경설정

#92 [feat] Jenkinsfile 작성완료.
  Jenkinsfile
Labels: 기능구현, 환경설정

#94 [refactor] 젠킨스 파일 url 부분 수정.
  Jenkinsfile
Labels: 리팩토링, 환경설정

#96 [fix] 환경변수 참조 오류 수정 1차 시도.
  Jenkinsfile
  config/settings.py
Labels: 오류수정

#98 [fix] 젠킨스 파일 2차 수정.
  Jenkinsfile
Labels: 오류수정

#100 [fix] 젠킨스 파일 3차 수정 완료.
  Jenkinsfile
Labels: 오류수정

#102 [fix] 도커 컴포즈 다운 명령어 추가.
  Jenkinsfile
Labels: 오류수정

#104 [fix] 젠킨스 파일 도커 명령어 추가.
  Jenkinsfile
Labels: 오류수정

#106 [fix] 환경변수 ID 수정.
  Jenkinsfile
Labels: 오류수정

#108 [fix] 젠킨스 파일 nginx 확인 스테이지 추가.
  Jenkinsfile
Labels: 오류수정

#110 [fix] 젠킨스파일 문법오류 수정.
  Jenkinsfile
Labels: 오류수정

#112 젠킨스 파일 nginx 마운트 경로문제 수정.
  Jenkinsfile
Labels: 오류수정

#114 [fix] 마운트 경로문제 2차 시도.
  Jenkinsfile
Labels: 오류수정

#116 [fix] 3차 시도
  Jenkinsfile
Labels: 오류수정

#118 [fix] 4차시도
  Jenkinsfile
Labels: 오류수정

#120 [fix] 5차 수정: 마운트 경로 및 nginx.conf 파일 수정
  docker-compose.yml
  nginx/nginx.conf
Labels: 오류수정

#122 [fix] 6차 시도
  docker-compose.yml
Labels: 오류수정

#124 [fix] 7차 시도.
  Jenkinsfile
Labels: 오류수정

#128 [feat] 젠킨스 파일 수정.
  Jenkinsfile
  docker-compose-jenkins.yml
  jenkins.Dockerfile
Labels: 기능구현, 오류수정

#130 [fix] 젠킨스파일 파이프라인 수정.
  Jenkinsfile
Labels: 오류수정

#132 [fix] 파이프라인 빌드 부분 메모리 제한 추가
  Jenkinsfile
Labels: 오류수정

#134 [fix] cpu 제한 삭제.
  Jenkinsfile
Labels: 오류수정

#137 [fix] cors 헤더 추가 허용.
  config/settings.py
Labels: 오류수정

#141 [refactor] 도커 환경 분리 1차.
  Dockerfile-celery
  Dockerfile-dev
  daphne/Dockerfile
  docker-compose.yml
  letsencrypt/.well-known/acme-challenge/test-file
  letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/ccc5c7eca5b25d0f4feba81cf4b8dcad/meta.json
  letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/ccc5c7eca5b25d0f4feba81cf4b8dcad/private_key.json
  letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/ccc5c7eca5b25d0f4feba81cf4b8dcad/regr.json
  nginx/Dockerfile
  nginx/nginx.conf
Labels: 기능구현, 리팩토링

#143 [fix] 도커파일명 수정.
  docker-compose.yml
Labels: 오류수정

#145 [fix] 젠킨스파일 도커파일명 수정.
  Jenkinsfile
Labels: 오류수정

#147 [feat] 엔진엑스 인증서 발급 전 테스트
  Jenkinsfile
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: 기능구현

#149 [feat] 엔진엑스 연동 1차
  docker-compose.yml
  letsencrypt/.well-known/acme-challenge/test-file
  letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/ccc5c7eca5b25d0f4feba81cf4b8dcad/meta.json
  letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/ccc5c7eca5b25d0f4feba81cf4b8dcad/private_key.json
  letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/ccc5c7eca5b25d0f4feba81cf4b8dcad/regr.json
  nginx/nginx.conf
Labels: 기능구현

#151 [fix] 배포오류수정
  Jenkinsfile
  docker-compose.yml
  letsencrypt/logs/letsencrypt.log
  letsencrypt/logs/letsencrypt.log.1
  letsencrypt/logs/letsencrypt.log.2
  letsencrypt/logs/letsencrypt.log.3
  letsencrypt/logs/letsencrypt.log.4
Labels: 오류수정

#153 [fix] 파이프라인 수정 및 도커컴포즈 수정
  Jenkinsfile
  docker-compose.yml
  nginx/nginx.conf
Labels: 오류수정

#155 [refactor] nginx.conf 수정
  nginx/nginx.conf
Labels: 리팩토링

#159 [refactor] 도커컴포즈 네트워크 통일
  docker-compose.yml
  letsencrypt/logs/letsencrypt.log
  letsencrypt/logs/letsencrypt.log.1
  letsencrypt/logs/letsencrypt.log.2
  letsencrypt/logs/letsencrypt.log.3
  letsencrypt/logs/letsencrypt.log.4
  letsencrypt/logs/letsencrypt.log.5
  letsencrypt/logs/letsencrypt.log.6
  letsencrypt/logs/letsencrypt.log.7
Labels: 리팩토링

#161 [fix] urls.py 수정
  config/urls.py
Labels: 오류수정

#163 [refactor] 도커컴포즈 수정
  config/urls.py
  docker-compose.yml
  letsencrypt/logs/letsencrypt.log
  letsencrypt/logs/letsencrypt.log.1
  letsencrypt/logs/letsencrypt.log.10
  letsencrypt/logs/letsencrypt.log.2
  letsencrypt/logs/letsencrypt.log.3
  letsencrypt/logs/letsencrypt.log.4
  letsencrypt/logs/letsencrypt.log.5
  letsencrypt/logs/letsencrypt.log.6
  letsencrypt/logs/letsencrypt.log.7
  letsencrypt/logs/letsencrypt.log.8
  letsencrypt/logs/letsencrypt.log.9
Labels: 리팩토링

#171 [feat] 2차 크롤링 정보로 ai 프롬프팅
  chat/chatgpt.py
  chat/consumers.py
  chat/routing.py
  chat/templates/websocket_test.html
  chat/views.py
  config/asgi.py
  config/settings.py
  docker-compose.yml
  letsencrypt/logs/letsencrypt.log.10
  letsencrypt/logs/letsencrypt.log.5
Labels: 기능구현

#173 [feat] 도커컴포즈 이미지 태그 업데이트
  docker-compose.yml
Labels: 환경설정

#175 [feat] gunicorn 연동
  Dockerfile-dev
Labels: 기능구현

#179 [feat] 도커컴포즈: 프로메테우스+그라파나 컨테이너 추가
  docker-compose.yml
Labels: 기능구현

#181 [refactor] 도커컴포즈 수정 및 supervisord 제거
  docker-compose.yml
  supervisord.conf
Labels: 리팩토링, 오류수정

#183 [feat] django-prometheus 추가 완료
  config/settings.py
  config/urls.py
  requirements.txt
Labels: 기능구현, 환경설정

#190 [refactor] 웹소켓 연동
  chat/consumers.py
  docker-compose.yml
Labels: 기능구현, 리팩토링

#192 [feat] 프로메테우스 노드 컨테이너 추가
  docker-compose.yml
Labels: 기능구현

#194 [feat] 도커컴포즈 프론트엔드 컨테이너 수정
  docker-compose.yml
Labels: 기능구현, 리팩토링

#198 [feat] 다프네 도커파일 uvicorn 세팅완료
  daphne/Dockerfile
Labels: 기능구현

#200 [refactor] 도커컴포즈 프론트 컨테이너 이미지 태그 수정
  docker-compose.yml
Labels: 리팩토링

#206 [feat] 프론트 컨테이너 이미지 태그 업데이트
  docker-compose.yml
Labels: 기능구현, 리팩토링
